"""Diff in-file search: inline prompt, match building, and navigation."""

from __future__ import annotations

from rit.ui.widgets.diff_search_bar import (
    close_search,
    handle_submitted_input,
    start_search,
)
from rit.ui.widgets.diff_search_commands import (
    clear_state,
    handle_changed,
    handle_submitted,
)
from rit.ui.widgets.diff_search_display import (
    refresh_search_display as _refresh_search_display,
)
from rit.ui.widgets.diff_search_matching import (
    search_highlight_spans,
    search_match_columns,
    search_match_style,
    search_matches_for_text,
    search_sides_for_line,
)
from rit.ui.widgets.diff_search_match_index import (
    apply_search_highlights,
    build_matches,
    next_match_index_from_cursor,
    refresh_matches,
    search_sides_for_row,
    sync_match_index_to_cursor,
)
from rit.ui.widgets.diff_search_navigation import (
    activate_match,
    jump_match,
    reveal_match,
)
from rit.ui.widgets.diff_search_policy import (
    next_search_match_index,
    search_activation_placement_update,
    search_activation_update,
    search_change_update,
    search_close_update,
    search_jump_target_index,
    search_jump_update,
    search_match_index_at_cursor,
    search_match_refresh,
    search_refresh_update,
    search_reveal_update,
    search_start_update,
    search_submission_request,
    search_submit_update,
    search_submitted_input_update,
)
from rit.ui.widgets.diff_search_types import (
    FlashStyle,
    SearchActivationPlacementAction,
    SearchActivationPlacementUpdate,
    SearchActivationUpdate,
    SearchChangeUpdate,
    SearchCloseAction,
    SearchCloseUpdate,
    SearchHighlightSpan,
    SearchJumpAction,
    SearchJumpUpdate,
    SearchMatchRefresh,
    SearchPane,
    SearchRefreshUpdate,
    SearchRevealAction,
    SearchRevealUpdate,
    SearchSide,
    SearchStartAction,
    SearchStartUpdate,
    SearchSubmissionAction,
    SearchSubmissionRequest,
    SearchSubmitAction,
    SearchSubmitUpdate,
    SearchSubmittedInputUpdate,
)
from rit.ui.widgets.diff_types import DiffSearchMatch

__all__ = (
    "DiffSearchMatch",
    "FlashStyle",
    "SearchActivationPlacementAction",
    "SearchActivationPlacementUpdate",
    "SearchActivationUpdate",
    "SearchChangeUpdate",
    "SearchCloseAction",
    "SearchCloseUpdate",
    "SearchHighlightSpan",
    "SearchJumpAction",
    "SearchJumpUpdate",
    "SearchMatchRefresh",
    "SearchPane",
    "SearchRefreshUpdate",
    "SearchRevealAction",
    "SearchRevealUpdate",
    "SearchSide",
    "SearchStartAction",
    "SearchStartUpdate",
    "SearchSubmissionAction",
    "SearchSubmissionRequest",
    "SearchSubmitAction",
    "SearchSubmitUpdate",
    "SearchSubmittedInputUpdate",
    "_refresh_search_display",
    "activate_match",
    "apply_search_highlights",
    "build_matches",
    "clear_state",
    "close_search",
    "handle_changed",
    "handle_submitted",
    "handle_submitted_input",
    "jump_match",
    "next_match_index_from_cursor",
    "next_search_match_index",
    "refresh_matches",
    "reveal_match",
    "search_activation_placement_update",
    "search_activation_update",
    "search_change_update",
    "search_close_update",
    "search_highlight_spans",
    "search_jump_target_index",
    "search_jump_update",
    "search_match_columns",
    "search_match_index_at_cursor",
    "search_match_refresh",
    "search_match_style",
    "search_matches_for_text",
    "search_refresh_update",
    "search_reveal_update",
    "search_sides_for_line",
    "search_sides_for_row",
    "search_start_update",
    "search_submission_request",
    "search_submit_update",
    "search_submitted_input_update",
    "start_search",
    "sync_match_index_to_cursor",
)
