import importlib


EXPECTED_SERVICE_REQUEST_EXPORTS = {
    "rit.services.graphql_mutations": {
        "GraphQLMutationError",
        "ThreadResolutionMutationError",
        "ThreadResolutionMutationRequest",
        "ensure_graphql_mutation_succeeded",
        "graphql_error_summary",
        "parse_thread_resolution_mutation_result",
        "parse_thread_resolution_mutation_succeeded",
        "parse_thread_resolution_result",
        "resolve_thread",
        "run_thread_resolution_mutation",
        "set_thread_resolution_state",
        "thread_resolution_mutation_request",
        "unresolve_thread",
    },
    "rit.services.pr_discussion": {
        "PRDiscussion",
        "discussion_from_pr",
        "fast_discussion_from_data",
        "fast_discussion_from_result",
        "fast_discussion_from_results",
        "fetch_pr_discussion",
        "fetch_pr_discussion_fast",
    },
    "rit.services.pr_file_pagination": {
        "OrderedPageItems",
        "PR_FILES_MAX_REST_PAGES",
        "PR_FILES_PAGE_CONCURRENCY",
        "PR_FILES_PER_PAGE",
        "PRFilePageProgress",
        "collect_all_page_items",
        "collect_ordered_page_items",
        "collect_page_batches",
    },
    "rit.services.pr_file_request": {
        "fetch_file_content",
        "fetch_pr_file_pages",
        "fetch_pr_files",
        "fetch_pr_files_page",
        "file_content_request",
        "parse_pr_files_page",
        "parse_pr_files_result",
        "pr_files_page_request",
    },
    "rit.services.pr_file_view_states": {
        "FileViewMutationError",
        "FileViewMutationRequest",
        "FileViewStatesGraphQLError",
        "FileViewStatesPage",
        "collect_file_view_states",
        "ensure_file_view_mutation_result",
        "ensure_file_view_mutation_succeeded",
        "fetch_file_view_states",
        "file_view_mutation_request",
        "file_view_states_page_request",
        "mark_file_as_viewed",
        "parse_file_view_states_page",
        "parse_file_view_states_result",
        "set_file_viewed_state",
        "unmark_file_as_viewed",
    },
    "rit.services.pr_graphql_queries": {
        "PullRequestGraphQLView",
        "pull_request_graphql_request",
        "pull_request_query",
    },
    "rit.services.pr_graphql_response": {
        "PullRequestGraphQLError",
        "PullRequestNotFound",
        "fetch_pull_request_all",
        "fetch_pull_request_graphql_node_id",
        "fetch_pull_request_graphql_pr",
        "fetch_pull_request_graphql_result",
        "fetch_pull_request_summary",
        "parse_pull_request_graphql_data",
        "parse_pull_request_graphql_node_id_result",
        "parse_pull_request_graphql_pr",
        "parse_pull_request_graphql_pr_result",
        "parse_pull_request_graphql_result",
    },
    "rit.services.pr_raw_diff": {
        "async_iter_pr_diff_sections",
        "async_iter_url_diff_sections",
        "fetch_pr_diff_text",
        "fetch_url_text",
        "iter_diff_sections",
        "iter_url_diff_sections",
        "pr_diff_url",
    },
    "rit.services.pr_review_request": {
        "create_issue_comment",
        "create_issue_comment_request",
        "create_pending_review",
        "create_pending_review_request",
        "create_review_comment",
        "delete_pending_review",
        "delete_pending_review_request",
        "list_review_comments",
        "list_review_comments_request",
        "parse_issue_comment_response",
        "parse_review_comments_response",
        "parse_review_response",
        "pull_request_review_comments_request",
        "run_review_request",
        "submit_pending_review",
        "submit_pending_review_request",
        "submit_review",
        "submit_review_request",
    },
    "rit.services.pr_reviewer_request": {
        "ParticipantChangeRequest",
        "add_assignees",
        "assignee_candidates_request",
        "assignee_change_request",
        "assignee_payload",
        "assignee_request",
        "fetch_assignee_candidates",
        "fetch_reviewer_candidates",
        "fetch_reviewer_team_candidates",
        "fetch_reviewer_user_candidates",
        "parse_reviewer_team_candidates",
        "parse_reviewer_user_candidates",
        "remove_assignees",
        "remove_requested_reviewers",
        "request_reviewers",
        "reviewer_change_request",
        "reviewer_payload",
        "reviewer_request",
        "reviewer_team_candidates_request",
        "reviewer_user_candidates_request",
        "run_participant_change",
        "should_treat_team_candidates_error_as_empty",
    },
}


def test_service_request_modules_export_documented_surfaces() -> None:
    for module_name, expected_exports in EXPECTED_SERVICE_REQUEST_EXPORTS.items():
        module = importlib.import_module(module_name)
        exports = tuple(module.__all__)

        assert set(exports) == expected_exports
        assert len(exports) == len(set(exports))
        assert exports == tuple(sorted(exports))
        for name in exports:
            assert hasattr(module, name)
