from typing import Protocol, runtime_checkable

__all__ = ("NavigableProtocol",)


@runtime_checkable
class NavigableProtocol(Protocol):
    def next_item(self) -> None: ...
    def prev_item(self) -> None: ...
    def select_item(self, index: int) -> None: ...
    def get_current_index(self) -> int: ...
    def get_item_count(self) -> int: ...
